# Compilers and options:

CC              = 
CPPFLAGS        =

OBJ_DEF   = kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib \
            advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib    \
            odbc32.lib odbccp32.lib opengl32.lib glaux.lib glu32.lib
OBJ_LIST1 = test.obj

all : test.exe 

test.exe:         $(OBJ_LIST1)
        link $(OBJ_LIST1) $(OBJ_DEF)
