OBJ_LIST =  $(OUTDIR)\array.obj    			\
			$(OUTDIR)\error.obj    			\
			$(OUTDIR)\memory.obj   			\
			$(OUTDIR)\obstack.obj  			\
			$(OUTDIR)\odemath.obj  			\
			$(OUTDIR)\matrix.obj   			\
			$(OUTDIR)\misc.obj     			\
			$(OUTDIR)\rotation.obj 			\
			$(OUTDIR)\mass.obj     			\
			$(OUTDIR)\ode.obj      			\
			$(OUTDIR)\step.obj     			\
			$(OUTDIR)\lcp.obj      			\
			$(OUTDIR)\joint.obj    			\
			$(OUTDIR)\timer.obj    			\
			$(OUTDIR)\mat.obj      			\
			$(OUTDIR)\testing.obj  			\
			$(OUTDIR)\fastdot.obj			\
			$(OUTDIR)\fastldlt.obj			\
			$(OUTDIR)\fastlsolve.obj		\
            $(OUTDIR)\fastltsolve.obj		\
			$(OUTDIR)\collision_util.obj  	\
			$(OUTDIR)\collision_std.obj  	\
			$(OUTDIR)\collision_space.obj  	\
			$(OUTDIR)\collision_kernel.obj	\
			$(OUTDIR)\collision_transform.obj

