foldersTree = gFld("<b>FreeImagePlus</b>", "", "")
     insDoc(foldersTree, gLnk("Main Page", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("FreeImage.h", "", ""))
       insDoc(aux1, gLnk("FreeImagePlus.h", "", ""))
aux1 = insFld(foldersTree, gFld("Compound List", "", "annotated.html"))
       insDoc(aux1, gLnk("fipGenericImage", "", "classfipGenericImage.html"))
       insDoc(aux1, gLnk("fipImage", "", "classfipImage.html"))
       insDoc(aux1, gLnk("fipWinImage", "", "classfipWinImage.html"))
       insDoc(aux1, gLnk("tagFreeImageComplex", "", "structtagFreeImageComplex.html"))
aux1 = insFld(foldersTree, gFld("Class Hierarchy", "", "hierarchy.html"))
  aux2 = insFld(aux1, gFld("fipGenericImage", "", "classfipGenericImage.html"))
    aux3 = insFld(aux2, gFld("fipImage", "", "classfipImage.html"))
           insDoc(aux3, gLnk("fipWinImage", "", "classfipWinImage.html"))
       insDoc(aux1, gLnk("tagBITMAPINFO", "", ""))
       insDoc(aux1, gLnk("tagBITMAPINFOHEADER", "", ""))
       insDoc(aux1, gLnk("tagFreeImageComplex", "", "structtagFreeImageComplex.html"))
       insDoc(aux1, gLnk("tagRGBQUAD", "", ""))
     insDoc(foldersTree, gLnk("Compound Members", "", "functions.html"))
