OBJ_LIST = $(OUTDIR)\pool.obj     \
           $(OUTDIR)\memory.obj   \
           $(OUTDIR)\system.obj   \
           $(OUTDIR)\flat.obj     \
           $(OUTDIR)\float.obj    \
           $(OUTDIR)\clpool.obj   \
           $(OUTDIR)\temp.obj     \
           $(OUTDIR)\dpool.obj    \
#           $(OUTDIR)\hpool.obj    \
           $(OUTDIR)\xpool.obj    \
           $(OUTDIR)\flcache.obj  \
           $(OUTDIR)\swap.obj     
