OBJ_LIST =  $(OUTDIR)\BinFile.obj  \
            $(OUTDIR)\SysFile.obj \
            $(OUTDIR)\MemFile.obj \
            $(OUTDIR)\CacheFile.obj \
            $(OUTDIR)\FrameFile.obj \
            $(OUTDIR)\PackFile.obj \
            $(OUTDIR)\ZipPack.obj \
            $(OUTDIR)\DiskPack.obj \
            $(OUTDIR)\FastPathPack.obj \
            $(OUTDIR)\unzip.obj     \
            $(OUTDIR)\PackStream.obj \
            $(OUTDIR)\StreamFile.obj
