OBJ_LIST = $(OUTDIR)\x3f.obj             \
           $(OUTDIR)\3ds.obj            \
           $(OUTDIR)\textenv.obj        \
           $(OUTDIR)\bmp.obj            \
           $(OUTDIR)\jpeg.obj           \
           $(OUTDIR)\tga.obj            \
           $(OUTDIR)\alp.obj            \
           $(OUTDIR)\font.obj           \
           $(OUTDIR)\utils.obj          \
           $(OUTDIR)\anim.obj           \
           $(OUTDIR)\hlpdraw.obj        \
           $(OUTDIR)\strip.obj          \
           $(OUTDIR)\euler.obj          \